"""initial schema

Revision ID: a96bf3d3af8d
Revises: 
Create Date: 2026-03-11 21:05:47.498450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a96bf3d3af8d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('background_tasks',
    sa.Column('task_type', sa.String(length=50), nullable=False, comment='poll_feasibility | poll_order_confirmation'),
    sa.Column('payload', sa.Text(), nullable=False, comment='JSON-encoded task parameters'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending | running | completed | failed'),
    sa.Column('result', sa.Text(), nullable=True, comment='JSON-encoded task result or error'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('background_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_background_tasks_status'), ['status'], unique=False)

    op.create_table('geocode_cache',
    sa.Column('place_name', sa.String(length=500), nullable=False, comment='Normalized place name used as the lookup key'),
    sa.Column('display_name', sa.Text(), nullable=True, comment='Full human-readable resolved place name from OSM'),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True, comment='JSON-encoded raw OSM response'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('geocode_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_geocode_cache_place_name'), ['place_name'], unique=False)

    op.create_table('notification_registry',
    sa.Column('id', sa.Uuid(), nullable=False, comment='SkyFi notification_id (the primary key IS the notification ID)'),
    sa.Column('api_key_hash', sa.String(length=64), nullable=False, comment='SHA-256 of the API key that created this notification'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_registry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_registry_api_key_hash'), ['api_key_hash'], unique=False)

    op.create_table('order_confirmations',
    sa.Column('token_hash', sa.String(length=64), nullable=False, comment='SHA-256 hex digest of the Fernet URL token'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending | confirmed | placed | expired | cancelled'),
    sa.Column('order_type', sa.String(length=20), nullable=False, comment='TASKING or ARCHIVE'),
    sa.Column('api_key_hash', sa.String(length=64), nullable=False, comment='SHA-256 hex digest of the SkyFi API key (for SSE routing)'),
    sa.Column('mcp_session_id', sa.String(length=255), nullable=True, comment='MCP session ID for SSE notification routing'),
    sa.Column('skyfi_order_id', sa.Uuid(), nullable=True, comment='Set after the order is successfully placed with SkyFi'),
    sa.Column('estimated_cost_cents', sa.Integer(), nullable=True, comment='Estimated cost shown on the confirmation page'),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_confirmations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_confirmations_api_key_hash'), ['api_key_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_confirmations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_confirmations_token_hash'), ['token_hash'], unique=True)

    op.create_table('webhook_events',
    sa.Column('event_type', sa.String(length=50), nullable=False, comment='order_status | archive_notification'),
    sa.Column('payload', sa.Text(), nullable=False, comment='Raw JSON payload from SkyFi'),
    sa.Column('api_key_hash', sa.String(length=64), nullable=True, comment='SHA-256 of the owning API key (for reconnect delivery routing)'),
    sa.Column('delivered', sa.Boolean(), nullable=False, comment='Whether this event has been delivered to an active session'),
    sa.Column('event_id', sa.String(length=255), nullable=True, comment='SkyFi-provided event ID for idempotency deduplication'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_events_api_key_hash'), ['api_key_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_events_delivered'), ['delivered'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_events_delivered'))
        batch_op.drop_index(batch_op.f('ix_webhook_events_api_key_hash'))

    op.drop_table('webhook_events')
    with op.batch_alter_table('order_confirmations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_confirmations_token_hash'))
        batch_op.drop_index(batch_op.f('ix_order_confirmations_status'))
        batch_op.drop_index(batch_op.f('ix_order_confirmations_api_key_hash'))

    op.drop_table('order_confirmations')
    with op.batch_alter_table('notification_registry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_registry_api_key_hash'))

    op.drop_table('notification_registry')
    with op.batch_alter_table('geocode_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_geocode_cache_place_name'))

    op.drop_table('geocode_cache')
    with op.batch_alter_table('background_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_background_tasks_status'))

    op.drop_table('background_tasks')
    # ### end Alembic commands ###
